# Compute the absolut volume of all tetrahedra of the unstructured input mesh:
pdi = self.GetInput()
pdo = self.GetOutput()
newData = vtk.vtkDoubleArray()
newData.SetName("Volume")
numTets = pdi.GetNumberOfCells()
for i in range(numTets):
       cell = pdi.GetCell(i)
       p1 = pdi.GetPoint(cell.GetPointId(0))
       p2 = pdi.GetPoint(cell.GetPointId(1))
       p3 = pdi.GetPoint(cell.GetPointId(2))
       p4 = pdi.GetPoint(cell.GetPointId(3))
       volume = vtk.vtkTetra.ComputeVolume(p1,p2,p3,p4)
       newData.InsertNextValue(abs(volume))
pdo.GetCellData().AddArray(newData)